image: node:12
pipelines:
    default:
        - step:
            script:
                # install dependencies
                - apt-get update
                - apt-get --yes install zip
                - npm install -g grunt-cli
                - npm install -g json
                - npm install

                # run some checks
                - npm run formatting:check

                # build the project
                - npm run build

                # get the current name/version of the project
                - NAME=$(json -f ./package.json name)
                - VERSION=$(json -f ./package.json version)

                # zip the output
                - pushd "./release/${NAME}_${VERSION}"
                - zip -r "../../${NAME}_${VERSION}.zip" *
                - popd

                # upload to the 'downloads' section of the bitbucket project
                - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/drk4/tetris/downloads" --form files=@"${NAME}_${VERSION}.zip"
